// src/lib/sample-data.ts
import { Activity, Category, Review } from './types';

export const categories: Category[] = [
  { id: '1', name: 'Sport Fishing', nameEs: 'Pesca Deportiva', slug: 'sport-fishing', description: 'World-class sportfishing in the Marlin Capital', icon: 'fish', image: null, sortOrder: 1 },
  { id: '2', name: 'Snorkel & Diving', nameEs: 'Snorkel y Buceo', slug: 'snorkel-diving', description: 'Explore the underwater world of the Sea of Cortez', icon: 'waves', image: null, sortOrder: 2 },
  { id: '3', name: 'Boat Tours', nameEs: 'Tours en Lancha', slug: 'boat-tours', description: 'Whale watching, glass bottom boats, coastal cruises', icon: 'ship', image: null, sortOrder: 3 },
  { id: '4', name: 'ATV & Land', nameEs: 'ATV y Aventuras', slug: 'atv-land', description: 'Off-road desert adventures', icon: 'mountain', image: null, sortOrder: 4 },
  { id: '5', name: 'Sailing & Cruises', nameEs: 'Veleros y Cruceros', slug: 'sailing-cruises', description: 'Sunset sails and luxury catamarans', icon: 'sailboat', image: null, sortOrder: 5 },
  { id: '6', name: 'Water Sports', nameEs: 'Deportes Acuáticos', slug: 'water-sports', description: 'Jet skis, flyboards, parasailing', icon: 'droplets', image: null, sortOrder: 6 },
  { id: '7', name: 'Cultural Tours', nameEs: 'Tours Culturales', slug: 'cultural-tours', description: 'History, art, and culture of Los Cabos', icon: 'landmark', image: null, sortOrder: 7 },
  { id: '8', name: 'Food & Drinks', nameEs: 'Gastronomía', slug: 'food-drinks', description: 'Taco tours, tequila tastings, culinary experiences', icon: 'utensils', image: null, sortOrder: 8 },
];

export const sampleReviews: Review[] = [
  { id: 'r1', rating: 5, title: 'Best experience ever!', comment: 'This was the highlight of our Cabo trip. The crew was amazing and professional.', images: [], createdAt: '2025-12-15T10:00:00Z', user: { name: 'Sarah M.', image: null } },
  { id: 'r2', rating: 5, title: 'Absolutely incredible', comment: 'Everything exceeded our expectations. The scenery was breathtaking and guides were knowledgeable.', images: [], createdAt: '2025-11-20T10:00:00Z', user: { name: 'Mike T.', image: null } },
  { id: 'r3', rating: 4, title: 'Great value', comment: 'Really well organized tour with excellent equipment. Highly recommended for families.', images: [], createdAt: '2025-11-05T10:00:00Z', user: { name: 'Emma R.', image: null } },
];

export const activities: Activity[] = [
  {
    id: 'a1',
    title: 'Deep Sea Marlin Fishing Charter',
    titleEs: 'Charter de Pesca de Marlín en Alta Mar',
    slug: 'deep-sea-marlin-fishing',
    description: 'Experience world-class sportfishing in Cabo San Lucas, the undisputed Marlin Capital of the World. Board a fully equipped 31-foot Bertram yacht and head out into the deep blue waters where the Pacific Ocean meets the Sea of Cortez. Our experienced captains know exactly where to find the big ones — striped marlin, blue marlin, yellowfin tuna, dorado (mahi-mahi), and wahoo. All tackle, bait, and fishing licenses are included. Whether you\'re a seasoned angler or casting your first line, our crew will make sure you have the catch of a lifetime.',
    shortDesc: 'Chase marlin, tuna, and dorado on a premium deep-sea fishing charter.',
    highlights: ['Premium 31ft Bertram yacht', 'Professional captain & crew', 'All tackle & bait included', 'Fishing license included', 'Cooler with ice, water & soft drinks', 'Hotel pickup in Cabo corridor'],
    notIncluded: ['Gratuities for crew', 'Alcoholic beverages', 'Sunscreen'],
    requirements: ['Sunscreen', 'Sunglasses', 'Light jacket', 'Camera'],
    duration: 480,
    maxCapacity: 6,
    priceAdult: 350,
    priceChild: 250,
    priceCurrency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200',
      'https://images.unsplash.com/photo-1504472478235-9bc48ba4d60f?w=1200',
      'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=1200',
    ],
    mainImage: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200',
    meetingPoint: 'Cabo San Lucas Marina, Dock C',
    meetingLat: 22.8825,
    meetingLng: -109.9058,
    cancellationPolicy: 'Free cancellation up to 48 hours before.',
    minAge: null,
    difficulty: 'moderate',
    languages: ['en', 'es'],
    isActive: true,
    isFeatured: true,
    avgRating: 4.8,
    totalReviews: 127,
    totalBookings: 850,
    categoryId: '1',
    operatorId: 'op1',
    category: categories[0],
    operator: { name: 'Pisces Sportfishing', companyName: 'Pisces Sportfishing' },
    reviews: sampleReviews,
  },
  {
    id: 'a2',
    title: "Snorkel at Pelican Rock & Lover's Beach",
    titleEs: 'Snorkel en Roca Pelícano y Playa del Amor',
    slug: 'snorkel-pelican-rock',
    description: "Discover the stunning underwater paradise of Cabo San Lucas. Glide through the crystal-clear waters of Pelican Rock where you'll encounter tropical fish, sea lions, and coral formations. Then visit the iconic Lover's Beach at the tip of the Baja Peninsula near El Arco.",
    shortDesc: "Snorkel with tropical fish and sea lions at Cabo's most iconic spots.",
    highlights: ['Professional snorkel equipment', 'Certified bilingual guide', 'Glass-bottom boat ride', "Visit to El Arco & Lover's Beach", 'Underwater photos included', 'Small group (max 12)'],
    notIncluded: ['Hotel transportation', 'Wetsuit rental ($10)'],
    requirements: ['Swimsuit', 'Towel', 'Biodegradable sunscreen'],
    duration: 180,
    maxCapacity: 12,
    priceAdult: 65,
    priceChild: 45,
    priceCurrency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1544551763-77ef2d0cfc6c?w=1200',
      'https://images.unsplash.com/photo-1682687220742-aba13b6e50ba?w=1200',
      'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=1200',
    ],
    mainImage: 'https://images.unsplash.com/photo-1544551763-77ef2d0cfc6c?w=1200',
    meetingPoint: 'Medano Beach, near The Office restaurant',
    meetingLat: 22.8838,
    meetingLng: -109.9011,
    cancellationPolicy: 'Free cancellation up to 24 hours before.',
    minAge: 6,
    difficulty: 'easy',
    languages: ['en', 'es'],
    isActive: true,
    isFeatured: true,
    avgRating: 4.9,
    totalReviews: 312,
    totalBookings: 2100,
    categoryId: '2',
    operatorId: 'op1',
    category: categories[1],
    operator: { name: 'Cabo Adventures', companyName: 'Cabo Adventures' },
    reviews: sampleReviews,
  },
  {
    id: 'a3',
    title: 'Whale Watching Eco-Tour',
    titleEs: 'Tour Ecológico de Avistamiento de Ballenas',
    slug: 'whale-watching-eco-tour',
    description: 'Witness majestic humpback and gray whales in their natural habitat during their annual migration. Expert marine biologist guides share fascinating facts while ensuring responsible whale-watching.',
    shortDesc: 'Get up close with humpback whales on a marine biologist-led eco-tour.',
    highlights: ['Marine biologist guide', 'Specialized zodiac boat', 'Hydrophone to hear whale songs', 'Whale sighting guarantee*', 'Certified eco-friendly tour'],
    notIncluded: ['Hotel pickup', 'Rain gear'],
    requirements: ['Warm layer', 'Camera with zoom', 'Sea sickness medication if needed'],
    duration: 150,
    maxCapacity: 16,
    priceAdult: 85,
    priceChild: 55,
    priceCurrency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1568430462989-44163eb1752f?w=1200',
      'https://images.unsplash.com/photo-1570913149827-d2ac84ab3f9a?w=1200',
      'https://images.unsplash.com/photo-1511159817101-f7f14839dd50?w=1200',
    ],
    mainImage: 'https://images.unsplash.com/photo-1568430462989-44163eb1752f?w=1200',
    meetingPoint: 'Cabo San Lucas Marina, Main Dock',
    meetingLat: 22.8825,
    meetingLng: -109.9058,
    cancellationPolicy: 'Full refund if no whales spotted.',
    minAge: 4,
    difficulty: 'easy',
    languages: ['en', 'es'],
    isActive: true,
    isFeatured: true,
    avgRating: 4.9,
    totalReviews: 489,
    totalBookings: 3200,
    categoryId: '3',
    operatorId: 'op1',
    category: categories[2],
    operator: { name: 'Cabo Adventures', companyName: 'Cabo Adventures' },
    reviews: sampleReviews,
  },
  {
    id: 'a4',
    title: 'Desert ATV & Beach Adventure',
    titleEs: 'ATV por el Desierto y Playa',
    slug: 'desert-atv-beach-adventure',
    description: 'Kick up dust on an exhilarating ATV ride through the Baja desert landscape with stunning Pacific coastline views.',
    shortDesc: 'Ride ATVs through Baja desert canyons to a hidden Pacific beach.',
    highlights: ['Polaris ATV', 'Professional guide', 'Safety equipment', 'Visit to traditional rancho', 'Beach stop', 'Hotel pickup & dropoff'],
    notIncluded: ['Photos ($25 USB)', 'Insurance upgrade'],
    requirements: ['Closed-toe shoes mandatory', 'Long pants', 'Valid driver license'],
    duration: 210,
    maxCapacity: 20,
    priceAdult: 95,
    priceChild: 65,
    priceCurrency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=1200',
      'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=1200',
      'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1200',
    ],
    mainImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=1200',
    meetingPoint: 'Rancho San Cristobal, Km 4.5',
    meetingLat: 22.9054,
    meetingLng: -109.9308,
    cancellationPolicy: 'Free cancellation up to 24 hours before.',
    minAge: 6,
    difficulty: 'moderate',
    languages: ['en', 'es'],
    isActive: true,
    isFeatured: false,
    avgRating: 4.7,
    totalReviews: 256,
    totalBookings: 1800,
    categoryId: '4',
    operatorId: 'op1',
    category: categories[3],
    operator: { name: 'Cabo Adventures', companyName: 'Cabo Adventures' },
    reviews: sampleReviews,
  },
  {
    id: 'a5',
    title: 'Luxury Sunset Sailing Cruise',
    titleEs: 'Crucero de Vela al Atardecer de Lujo',
    slug: 'luxury-sunset-sailing',
    description: 'Set sail aboard a stunning 42-foot luxury catamaran as the sun paints the sky over the Pacific. Premium open bar, gourmet appetizers, and live acoustic music.',
    shortDesc: 'Sail past El Arco on a luxury catamaran with open bar and live music.',
    highlights: ['42ft luxury catamaran', 'Premium open bar', 'Gourmet appetizers', 'Live acoustic music', 'Sail past El Arco', 'Champagne sunset toast'],
    notIncluded: ['Hotel transportation', 'Gratuities'],
    requirements: ['Light sweater', 'Camera'],
    duration: 150,
    maxCapacity: 24,
    priceAdult: 120,
    priceChild: 75,
    priceCurrency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1540946485063-a40da27545f8?w=1200',
      'https://images.unsplash.com/photo-1500514966906-fe245eea9344?w=1200',
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200',
    ],
    mainImage: 'https://images.unsplash.com/photo-1540946485063-a40da27545f8?w=1200',
    meetingPoint: 'Cabo San Lucas Marina, Dock E',
    meetingLat: 22.883,
    meetingLng: -109.9062,
    cancellationPolicy: 'Free cancellation up to 48 hours before.',
    minAge: 0,
    difficulty: 'easy',
    languages: ['en', 'es'],
    isActive: true,
    isFeatured: true,
    avgRating: 4.9,
    totalReviews: 567,
    totalBookings: 4500,
    categoryId: '5',
    operatorId: 'op2',
    category: categories[4],
    operator: { name: 'Cabo Sailing', companyName: 'Cabo Sailing Ocean Adventures' },
    reviews: sampleReviews,
  },
  {
    id: 'a6',
    title: 'Jet Ski & Flyboard Combo',
    titleEs: 'Combo Jet Ski y Flyboard',
    slug: 'jet-ski-flyboard-combo',
    description: 'Get your adrenaline pumping with this ultimate water sports combo in the warm waters of Medano Beach.',
    shortDesc: 'Ride jet skis along the coast then soar above the ocean on a flyboard.',
    highlights: ['30-min jet ski ride', '20-min flyboard session', 'Certified instructors', 'All safety equipment', 'On-beach location'],
    notIncluded: ['GoPro video ($30)', 'Hotel transportation'],
    requirements: ['Swimsuit', 'Must know how to swim'],
    duration: 90,
    maxCapacity: 8,
    priceAdult: 145,
    priceChild: null,
    priceCurrency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1530870110042-98b2cb110834?w=1200',
      'https://images.unsplash.com/photo-1596464716127-f2a82984de30?w=1200',
    ],
    mainImage: 'https://images.unsplash.com/photo-1530870110042-98b2cb110834?w=1200',
    meetingPoint: 'Medano Beach Water Sports Center',
    meetingLat: 22.8842,
    meetingLng: -109.9008,
    cancellationPolicy: 'Free cancellation up to 24 hours before.',
    minAge: 16,
    difficulty: 'moderate',
    languages: ['en', 'es'],
    isActive: true,
    isFeatured: false,
    avgRating: 4.6,
    totalReviews: 198,
    totalBookings: 950,
    categoryId: '6',
    operatorId: 'op1',
    category: categories[5],
    operator: { name: 'Cabo Adventures', companyName: 'Cabo Adventures' },
    reviews: sampleReviews,
  },
  {
    id: 'a7',
    title: 'San José del Cabo Art Walk & History Tour',
    titleEs: 'Caminata de Arte e Historia',
    slug: 'san-jose-art-walk-history',
    description: 'Discover the cultural heart of Los Cabos on this guided walking tour through San José del Cabo\'s historic Art District.',
    shortDesc: 'Explore galleries, colonial history, and mezcal on a guided art walk.',
    highlights: ['Local expert guide', 'Visit 6-8 galleries', 'Meet working artists', 'Mission visit', 'Mezcal tasting included', 'Small group (max 10)'],
    notIncluded: ['Artwork purchases', 'Dinner'],
    requirements: ['Comfortable shoes', 'Light clothing'],
    duration: 180,
    maxCapacity: 10,
    priceAdult: 55,
    priceChild: 35,
    priceCurrency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=1200',
      'https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=1200',
    ],
    mainImage: 'https://images.unsplash.com/photo-1582555172866-f73bb12a2ab3?w=1200',
    meetingPoint: 'San José del Cabo Town Square',
    meetingLat: 23.0578,
    meetingLng: -109.6987,
    cancellationPolicy: 'Free cancellation up to 24 hours before.',
    minAge: 0,
    difficulty: 'easy',
    languages: ['en', 'es'],
    isActive: true,
    isFeatured: false,
    avgRating: 4.8,
    totalReviews: 178,
    totalBookings: 1200,
    categoryId: '7',
    operatorId: 'op1',
    category: categories[6],
    operator: { name: 'Cabo Adventures', companyName: 'Cabo Adventures' },
    reviews: sampleReviews,
  },
  {
    id: 'a8',
    title: 'Taco Trail & Tequila Tasting Experience',
    titleEs: 'Ruta de Tacos y Degustación de Tequila',
    slug: 'taco-trail-tequila-tasting',
    description: 'Eat your way through the best culinary secrets of Cabo San Lucas on this mouth-watering food tour with tequila tasting.',
    shortDesc: 'Taste 12+ street tacos and premium tequilas with a local foodie guide.',
    highlights: ['Local foodie guide', '5 taco stops, 12+ tastings', 'Premium tequila tasting', '4 agave spirit pours', 'Vegetarian options available'],
    notIncluded: ['Additional drinks', 'Transportation to start'],
    requirements: ['Empty stomach!', 'Comfortable shoes'],
    duration: 210,
    maxCapacity: 12,
    priceAdult: 75,
    priceChild: 45,
    priceCurrency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=1200',
      'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=1200',
    ],
    mainImage: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=1200',
    meetingPoint: 'Boulevard Marina, Downtown Cabo',
    meetingLat: 22.8898,
    meetingLng: -109.905,
    cancellationPolicy: 'Free cancellation up to 24 hours before.',
    minAge: 12,
    difficulty: 'easy',
    languages: ['en', 'es'],
    isActive: true,
    isFeatured: true,
    avgRating: 4.9,
    totalReviews: 423,
    totalBookings: 2800,
    categoryId: '8',
    operatorId: 'op1',
    category: categories[7],
    operator: { name: 'Cabo Adventures', companyName: 'Cabo Adventures' },
    reviews: sampleReviews,
  },
  {
    id: 'a9',
    title: 'Cabo Arch & Sea Lion Colony Kayak Tour',
    titleEs: 'Tour en Kayak al Arco y Lobos Marinos',
    slug: 'arch-sea-lion-kayak',
    description: 'Paddle to El Arco, visit playful sea lions, then snorkel at Pelican Rock with crystal-clear visibility.',
    shortDesc: 'Kayak to El Arco, visit sea lions, and snorkel at Pelican Rock.',
    highlights: ['Guided kayak to El Arco', 'Sea lion colony visit', 'Snorkel at Pelican Rock', 'All equipment included', 'Photos from guide'],
    notIncluded: ['Transparent kayak upgrade ($15)', 'Wetsuit ($10)'],
    requirements: ['Swimsuit', 'Biodegradable sunscreen', 'Basic swimming ability'],
    duration: 150,
    maxCapacity: 14,
    priceAdult: 60,
    priceChild: 40,
    priceCurrency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1474552226712-ac0f0961a954?w=1200',
      'https://images.unsplash.com/photo-1530870110042-98b2cb110834?w=1200',
    ],
    mainImage: 'https://images.unsplash.com/photo-1474552226712-ac0f0961a954?w=1200',
    meetingPoint: 'Medano Beach, Cabo Kayak Hut',
    meetingLat: 22.884,
    meetingLng: -109.901,
    cancellationPolicy: 'Free cancellation up to 24 hours before.',
    minAge: 8,
    difficulty: 'moderate',
    languages: ['en', 'es'],
    isActive: true,
    isFeatured: false,
    avgRating: 4.7,
    totalReviews: 345,
    totalBookings: 2400,
    categoryId: '3',
    operatorId: 'op1',
    category: categories[2],
    operator: { name: 'Cabo Adventures', companyName: 'Cabo Adventures' },
    reviews: sampleReviews,
  },
  {
    id: 'a10',
    title: 'Glass-Bottom Boat & Snorkel at Chileno Bay',
    titleEs: 'Lancha Fondo de Cristal y Snorkel en Chileno',
    slug: 'glass-bottom-boat-chileno',
    description: 'See marine life through glass then snorkel a Blue Flag bay. Includes gourmet lunch, fresh ceviche, and open bar.',
    shortDesc: 'See marine life through glass then snorkel a Blue Flag bay with open bar.',
    highlights: ['Glass-bottom boat', 'Snorkel at Blue Flag beach', 'Gourmet box lunch', 'Fresh ceviche', 'Open bar', 'All snorkel equipment'],
    notIncluded: ['Hotel pickup', 'Underwater camera rental'],
    requirements: ['Swimsuit', 'Towel', 'Biodegradable sunscreen only'],
    duration: 240,
    maxCapacity: 30,
    priceAdult: 95,
    priceChild: 65,
    priceCurrency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=1200',
      'https://images.unsplash.com/photo-1682687220742-aba13b6e50ba?w=1200',
    ],
    mainImage: 'https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?w=1200',
    meetingPoint: 'Cabo San Lucas Marina, Dock A',
    meetingLat: 22.8827,
    meetingLng: -109.9056,
    cancellationPolicy: 'Free cancellation up to 24 hours before.',
    minAge: 3,
    difficulty: 'easy',
    languages: ['en', 'es'],
    isActive: true,
    isFeatured: false,
    avgRating: 4.6,
    totalReviews: 289,
    totalBookings: 1950,
    categoryId: '3',
    operatorId: 'op2',
    category: categories[2],
    operator: { name: 'Cabo Sailing', companyName: 'Cabo Sailing Ocean Adventures' },
    reviews: sampleReviews,
  },
];

export function getActivityBySlug(slug: string): Activity | undefined {
  return activities.find(a => a.slug === slug);
}

export function getActivitiesByCategory(categorySlug: string): Activity[] {
  const cat = categories.find(c => c.slug === categorySlug);
  if (!cat) return [];
  return activities.filter(a => a.categoryId === cat.id);
}

export function getFeaturedActivities(): Activity[] {
  return activities.filter(a => a.isFeatured);
}

export function formatDuration(minutes: number): string {
  if (minutes < 60) return `${minutes} min`;
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  return m > 0 ? `${h}h ${m}m` : `${h} hours`;
}

export function formatPrice(price: number): string {
  return `$${price.toLocaleString('en-US')}`;
}
